//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobarServicesTest.AprobarWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aprobar", Namespace="http://schemas.datacontract.org/2004/07/AprobarServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Aprobar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoEmpleadoApruebaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FeAprobadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRetornoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlagAprobadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SustentoViajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalSolicitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AprobarServicesTest.AprobarWS.Empleado empleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AprobarServicesTest.AprobarWS.Ubigeo ubigeoDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AprobarServicesTest.AprobarWS.Ubigeo ubigeoOrigenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoEmpleadoAprueba {
            get {
                return this.CodigoEmpleadoApruebaField;
            }
            set {
                if ((this.CodigoEmpleadoApruebaField.Equals(value) != true)) {
                    this.CodigoEmpleadoApruebaField = value;
                    this.RaisePropertyChanged("CodigoEmpleadoAprueba");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoSolicitud {
            get {
                return this.CodigoSolicitudField;
            }
            set {
                if ((this.CodigoSolicitudField.Equals(value) != true)) {
                    this.CodigoSolicitudField = value;
                    this.RaisePropertyChanged("CodigoSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FeAprobado {
            get {
                return this.FeAprobadoField;
            }
            set {
                if ((this.FeAprobadoField.Equals(value) != true)) {
                    this.FeAprobadoField = value;
                    this.RaisePropertyChanged("FeAprobado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRetorno {
            get {
                return this.FechaRetornoField;
            }
            set {
                if ((this.FechaRetornoField.Equals(value) != true)) {
                    this.FechaRetornoField = value;
                    this.RaisePropertyChanged("FechaRetorno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaSalida {
            get {
                return this.FechaSalidaField;
            }
            set {
                if ((this.FechaSalidaField.Equals(value) != true)) {
                    this.FechaSalidaField = value;
                    this.RaisePropertyChanged("FechaSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaSolicitud {
            get {
                return this.FechaSolicitudField;
            }
            set {
                if ((this.FechaSolicitudField.Equals(value) != true)) {
                    this.FechaSolicitudField = value;
                    this.RaisePropertyChanged("FechaSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlagAprobado {
            get {
                return this.FlagAprobadoField;
            }
            set {
                if ((object.ReferenceEquals(this.FlagAprobadoField, value) != true)) {
                    this.FlagAprobadoField = value;
                    this.RaisePropertyChanged("FlagAprobado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SustentoViaje {
            get {
                return this.SustentoViajeField;
            }
            set {
                if ((object.ReferenceEquals(this.SustentoViajeField, value) != true)) {
                    this.SustentoViajeField = value;
                    this.RaisePropertyChanged("SustentoViaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalSolicitado {
            get {
                return this.TotalSolicitadoField;
            }
            set {
                if ((this.TotalSolicitadoField.Equals(value) != true)) {
                    this.TotalSolicitadoField = value;
                    this.RaisePropertyChanged("TotalSolicitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AprobarServicesTest.AprobarWS.Empleado empleado {
            get {
                return this.empleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.empleadoField, value) != true)) {
                    this.empleadoField = value;
                    this.RaisePropertyChanged("empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AprobarServicesTest.AprobarWS.Ubigeo ubigeoDestino {
            get {
                return this.ubigeoDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.ubigeoDestinoField, value) != true)) {
                    this.ubigeoDestinoField = value;
                    this.RaisePropertyChanged("ubigeoDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AprobarServicesTest.AprobarWS.Ubigeo ubigeoOrigen {
            get {
                return this.ubigeoOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.ubigeoOrigenField, value) != true)) {
                    this.ubigeoOrigenField = value;
                    this.RaisePropertyChanged("ubigeoOrigen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/AprobarServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxAp_MaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxAp_PaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxPreNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoEmpleado {
            get {
                return this.CoEmpleadoField;
            }
            set {
                if ((this.CoEmpleadoField.Equals(value) != true)) {
                    this.CoEmpleadoField = value;
                    this.RaisePropertyChanged("CoEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxAp_Materno {
            get {
                return this.TxAp_MaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.TxAp_MaternoField, value) != true)) {
                    this.TxAp_MaternoField = value;
                    this.RaisePropertyChanged("TxAp_Materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxAp_Paterno {
            get {
                return this.TxAp_PaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.TxAp_PaternoField, value) != true)) {
                    this.TxAp_PaternoField = value;
                    this.RaisePropertyChanged("TxAp_Paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxPreNombre {
            get {
                return this.TxPreNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.TxPreNombreField, value) != true)) {
                    this.TxPreNombreField = value;
                    this.RaisePropertyChanged("TxPreNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ubigeo", Namespace="http://schemas.datacontract.org/2004/07/AprobarServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Ubigeo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoUbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoDescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoUbigeo {
            get {
                return this.CodigoUbigeoField;
            }
            set {
                if ((this.CodigoUbigeoField.Equals(value) != true)) {
                    this.CodigoUbigeoField = value;
                    this.RaisePropertyChanged("CodigoUbigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoDescripcion {
            get {
                return this.NoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.NoDescripcionField, value) != true)) {
                    this.NoDescripcionField = value;
                    this.RaisePropertyChanged("NoDescripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AprobarWS.IAprobaciones")]
    public interface IAprobaciones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAprobaciones/ObtenerSolicitud", ReplyAction="http://tempuri.org/IAprobaciones/ObtenerSolicitudResponse")]
        AprobarServicesTest.AprobarWS.Aprobar ObtenerSolicitud(int codigoSolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAprobaciones/ModificarSolicitud", ReplyAction="http://tempuri.org/IAprobaciones/ModificarSolicitudResponse")]
        AprobarServicesTest.AprobarWS.Aprobar ModificarSolicitud(int codigoSolicitud, int codigoEmpleadoSolicitante, int codigoUbigeoOrigen, int codigoUbigeoDestino, System.DateTime fechaSolicitud, System.DateTime fechaSalida, System.DateTime fechaRetorno, string sustentoViaje, double totalSolicitado, string flagAprobado, System.DateTime feAprobado, int CodigoEmpleadoAprueba);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAprobaciones/ListarSolicitudes", ReplyAction="http://tempuri.org/IAprobaciones/ListarSolicitudesResponse")]
        AprobarServicesTest.AprobarWS.Aprobar[] ListarSolicitudes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAprobaciones/ListarUbigeos", ReplyAction="http://tempuri.org/IAprobaciones/ListarUbigeosResponse")]
        AprobarServicesTest.AprobarWS.Ubigeo[] ListarUbigeos();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAprobacionesChannel : AprobarServicesTest.AprobarWS.IAprobaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AprobacionesClient : System.ServiceModel.ClientBase<AprobarServicesTest.AprobarWS.IAprobaciones>, AprobarServicesTest.AprobarWS.IAprobaciones {
        
        public AprobacionesClient() {
        }
        
        public AprobacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AprobacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AprobacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AprobacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AprobarServicesTest.AprobarWS.Aprobar ObtenerSolicitud(int codigoSolicitud) {
            return base.Channel.ObtenerSolicitud(codigoSolicitud);
        }
        
        public AprobarServicesTest.AprobarWS.Aprobar ModificarSolicitud(int codigoSolicitud, int codigoEmpleadoSolicitante, int codigoUbigeoOrigen, int codigoUbigeoDestino, System.DateTime fechaSolicitud, System.DateTime fechaSalida, System.DateTime fechaRetorno, string sustentoViaje, double totalSolicitado, string flagAprobado, System.DateTime feAprobado, int CodigoEmpleadoAprueba) {
            return base.Channel.ModificarSolicitud(codigoSolicitud, codigoEmpleadoSolicitante, codigoUbigeoOrigen, codigoUbigeoDestino, fechaSolicitud, fechaSalida, fechaRetorno, sustentoViaje, totalSolicitado, flagAprobado, feAprobado, CodigoEmpleadoAprueba);
        }
        
        public AprobarServicesTest.AprobarWS.Aprobar[] ListarSolicitudes() {
            return base.Channel.ListarSolicitudes();
        }
        
        public AprobarServicesTest.AprobarWS.Ubigeo[] ListarUbigeos() {
            return base.Channel.ListarUbigeos();
        }
    }
}
