//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlViaticosApp.LiquidacionesWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Liquidar", Namespace="http://schemas.datacontract.org/2004/07/LiquidarServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Liquidar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Co_LiquidacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlViaticosApp.LiquidacionesWS.LiquidarDetalle[] DetallesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fe_LiquidacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Ss_OtrosGastosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Ss_TotalAsignadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Ss_TotalUtilizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlViaticosApp.LiquidacionesWS.Solicitud solicitudField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Co_Liquidacion {
            get {
                return this.Co_LiquidacionField;
            }
            set {
                if ((this.Co_LiquidacionField.Equals(value) != true)) {
                    this.Co_LiquidacionField = value;
                    this.RaisePropertyChanged("Co_Liquidacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlViaticosApp.LiquidacionesWS.LiquidarDetalle[] Detalles {
            get {
                return this.DetallesField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallesField, value) != true)) {
                    this.DetallesField = value;
                    this.RaisePropertyChanged("Detalles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fe_Liquidacion {
            get {
                return this.Fe_LiquidacionField;
            }
            set {
                if ((this.Fe_LiquidacionField.Equals(value) != true)) {
                    this.Fe_LiquidacionField = value;
                    this.RaisePropertyChanged("Fe_Liquidacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Ss_OtrosGastos {
            get {
                return this.Ss_OtrosGastosField;
            }
            set {
                if ((this.Ss_OtrosGastosField.Equals(value) != true)) {
                    this.Ss_OtrosGastosField = value;
                    this.RaisePropertyChanged("Ss_OtrosGastos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Ss_TotalAsignado {
            get {
                return this.Ss_TotalAsignadoField;
            }
            set {
                if ((this.Ss_TotalAsignadoField.Equals(value) != true)) {
                    this.Ss_TotalAsignadoField = value;
                    this.RaisePropertyChanged("Ss_TotalAsignado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Ss_TotalUtilizado {
            get {
                return this.Ss_TotalUtilizadoField;
            }
            set {
                if ((this.Ss_TotalUtilizadoField.Equals(value) != true)) {
                    this.Ss_TotalUtilizadoField = value;
                    this.RaisePropertyChanged("Ss_TotalUtilizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlViaticosApp.LiquidacionesWS.Solicitud solicitud {
            get {
                return this.solicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.solicitudField, value) != true)) {
                    this.solicitudField = value;
                    this.RaisePropertyChanged("solicitud");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Solicitud", Namespace="http://schemas.datacontract.org/2004/07/LiquidarServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Solicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Co_EmpSolicitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Co_SolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlViaticosApp.LiquidacionesWS.SolicitudDetalle[] DetallesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fe_RetornoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fe_SalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fe_SolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Ss_TotalSolicitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tx_SustentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlViaticosApp.LiquidacionesWS.Ubigeo ubigeoDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlViaticosApp.LiquidacionesWS.Ubigeo ubigeoOrigenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Co_EmpSolicitante {
            get {
                return this.Co_EmpSolicitanteField;
            }
            set {
                if ((this.Co_EmpSolicitanteField.Equals(value) != true)) {
                    this.Co_EmpSolicitanteField = value;
                    this.RaisePropertyChanged("Co_EmpSolicitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Co_Solicitud {
            get {
                return this.Co_SolicitudField;
            }
            set {
                if ((this.Co_SolicitudField.Equals(value) != true)) {
                    this.Co_SolicitudField = value;
                    this.RaisePropertyChanged("Co_Solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlViaticosApp.LiquidacionesWS.SolicitudDetalle[] Detalles {
            get {
                return this.DetallesField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallesField, value) != true)) {
                    this.DetallesField = value;
                    this.RaisePropertyChanged("Detalles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fe_Retorno {
            get {
                return this.Fe_RetornoField;
            }
            set {
                if ((this.Fe_RetornoField.Equals(value) != true)) {
                    this.Fe_RetornoField = value;
                    this.RaisePropertyChanged("Fe_Retorno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fe_Salida {
            get {
                return this.Fe_SalidaField;
            }
            set {
                if ((this.Fe_SalidaField.Equals(value) != true)) {
                    this.Fe_SalidaField = value;
                    this.RaisePropertyChanged("Fe_Salida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fe_Solicitud {
            get {
                return this.Fe_SolicitudField;
            }
            set {
                if ((this.Fe_SolicitudField.Equals(value) != true)) {
                    this.Fe_SolicitudField = value;
                    this.RaisePropertyChanged("Fe_Solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Ss_TotalSolicitado {
            get {
                return this.Ss_TotalSolicitadoField;
            }
            set {
                if ((this.Ss_TotalSolicitadoField.Equals(value) != true)) {
                    this.Ss_TotalSolicitadoField = value;
                    this.RaisePropertyChanged("Ss_TotalSolicitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tx_Sustento {
            get {
                return this.Tx_SustentoField;
            }
            set {
                if ((object.ReferenceEquals(this.Tx_SustentoField, value) != true)) {
                    this.Tx_SustentoField = value;
                    this.RaisePropertyChanged("Tx_Sustento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlViaticosApp.LiquidacionesWS.Ubigeo ubigeoDestino {
            get {
                return this.ubigeoDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.ubigeoDestinoField, value) != true)) {
                    this.ubigeoDestinoField = value;
                    this.RaisePropertyChanged("ubigeoDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlViaticosApp.LiquidacionesWS.Ubigeo ubigeoOrigen {
            get {
                return this.ubigeoOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.ubigeoOrigenField, value) != true)) {
                    this.ubigeoOrigenField = value;
                    this.RaisePropertyChanged("ubigeoOrigen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LiquidarDetalle", Namespace="http://schemas.datacontract.org/2004/07/LiquidarServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class LiquidarDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlViaticosApp.LiquidacionesWS.LiquidarDetallePK PKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Ss_MontoAsignadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Ss_MontoUtilizadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlViaticosApp.LiquidacionesWS.LiquidarDetallePK PK {
            get {
                return this.PKField;
            }
            set {
                if ((object.ReferenceEquals(this.PKField, value) != true)) {
                    this.PKField = value;
                    this.RaisePropertyChanged("PK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Ss_MontoAsignado {
            get {
                return this.Ss_MontoAsignadoField;
            }
            set {
                if ((this.Ss_MontoAsignadoField.Equals(value) != true)) {
                    this.Ss_MontoAsignadoField = value;
                    this.RaisePropertyChanged("Ss_MontoAsignado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Ss_MontoUtilizado {
            get {
                return this.Ss_MontoUtilizadoField;
            }
            set {
                if ((this.Ss_MontoUtilizadoField.Equals(value) != true)) {
                    this.Ss_MontoUtilizadoField = value;
                    this.RaisePropertyChanged("Ss_MontoUtilizado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LiquidarDetallePK", Namespace="http://schemas.datacontract.org/2004/07/LiquidarServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class LiquidarDetallePK : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LiquidarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlViaticosApp.LiquidacionesWS.TipoViatico TipoViaticoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Liquidar {
            get {
                return this.LiquidarField;
            }
            set {
                if ((this.LiquidarField.Equals(value) != true)) {
                    this.LiquidarField = value;
                    this.RaisePropertyChanged("Liquidar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlViaticosApp.LiquidacionesWS.TipoViatico TipoViatico {
            get {
                return this.TipoViaticoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoViaticoField, value) != true)) {
                    this.TipoViaticoField = value;
                    this.RaisePropertyChanged("TipoViatico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoViatico", Namespace="http://schemas.datacontract.org/2004/07/LiquidarServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class TipoViatico : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Co_TipoViaticoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string No_DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Co_TipoViatico {
            get {
                return this.Co_TipoViaticoField;
            }
            set {
                if ((this.Co_TipoViaticoField.Equals(value) != true)) {
                    this.Co_TipoViaticoField = value;
                    this.RaisePropertyChanged("Co_TipoViatico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No_Descripcion {
            get {
                return this.No_DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.No_DescripcionField, value) != true)) {
                    this.No_DescripcionField = value;
                    this.RaisePropertyChanged("No_Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ubigeo", Namespace="http://schemas.datacontract.org/2004/07/LiquidarServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Ubigeo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoUbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoDescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoUbigeo {
            get {
                return this.CodigoUbigeoField;
            }
            set {
                if ((this.CodigoUbigeoField.Equals(value) != true)) {
                    this.CodigoUbigeoField = value;
                    this.RaisePropertyChanged("CodigoUbigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoDescripcion {
            get {
                return this.NoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.NoDescripcionField, value) != true)) {
                    this.NoDescripcionField = value;
                    this.RaisePropertyChanged("NoDescripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudDetalle", Namespace="http://schemas.datacontract.org/2004/07/LiquidarServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class SolicitudDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlViaticosApp.LiquidacionesWS.SolicitudDetallePK PKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Ss_MontoSolicitadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlViaticosApp.LiquidacionesWS.SolicitudDetallePK PK {
            get {
                return this.PKField;
            }
            set {
                if ((object.ReferenceEquals(this.PKField, value) != true)) {
                    this.PKField = value;
                    this.RaisePropertyChanged("PK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Ss_MontoSolicitado {
            get {
                return this.Ss_MontoSolicitadoField;
            }
            set {
                if ((this.Ss_MontoSolicitadoField.Equals(value) != true)) {
                    this.Ss_MontoSolicitadoField = value;
                    this.RaisePropertyChanged("Ss_MontoSolicitado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudDetallePK", Namespace="http://schemas.datacontract.org/2004/07/LiquidarServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class SolicitudDetallePK : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlViaticosApp.LiquidacionesWS.TipoViatico TipoViaticoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Solicitud {
            get {
                return this.SolicitudField;
            }
            set {
                if ((this.SolicitudField.Equals(value) != true)) {
                    this.SolicitudField = value;
                    this.RaisePropertyChanged("Solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlViaticosApp.LiquidacionesWS.TipoViatico TipoViatico {
            get {
                return this.TipoViaticoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoViaticoField, value) != true)) {
                    this.TipoViaticoField = value;
                    this.RaisePropertyChanged("TipoViatico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/LiquidarServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Co_TipoViaticoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Ss_MontoUtilizadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Co_TipoViatico {
            get {
                return this.Co_TipoViaticoField;
            }
            set {
                if ((this.Co_TipoViaticoField.Equals(value) != true)) {
                    this.Co_TipoViaticoField = value;
                    this.RaisePropertyChanged("Co_TipoViatico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Ss_MontoUtilizado {
            get {
                return this.Ss_MontoUtilizadoField;
            }
            set {
                if ((this.Ss_MontoUtilizadoField.Equals(value) != true)) {
                    this.Ss_MontoUtilizadoField = value;
                    this.RaisePropertyChanged("Ss_MontoUtilizado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/LiquidarServices.Persistencia")]
    [System.SerializableAttribute()]
    public partial class ValidationException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((this.CodigoErrorField.Equals(value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LiquidacionesWS.ILiquidaciones")]
    public interface ILiquidaciones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidaciones/ObtenerLiquidacion", ReplyAction="http://tempuri.org/ILiquidaciones/ObtenerLiquidacionResponse")]
        ControlViaticosApp.LiquidacionesWS.Liquidar ObtenerLiquidacion(int CoLiquidacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidaciones/ModificarLiquidacion", ReplyAction="http://tempuri.org/ILiquidaciones/ModificarLiquidacionResponse")]
        ControlViaticosApp.LiquidacionesWS.Liquidar ModificarLiquidacion(int CoLiquidacion, System.DateTime FeLiquidacion, int CoSolicitud, double SsTotalAsignado, double SsTotalUtilizado, double SsOtrosGastos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidaciones/EliminarLiquidacion", ReplyAction="http://tempuri.org/ILiquidaciones/EliminarLiquidacionResponse")]
        void EliminarLiquidacion(int CoLiquidacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidaciones/CrearLiquidacion", ReplyAction="http://tempuri.org/ILiquidaciones/CrearLiquidacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControlViaticosApp.LiquidacionesWS.ValidationException), Action="http://tempuri.org/ILiquidaciones/CrearLiquidacionValidationExceptionFault", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/LiquidarServices.Persistencia")]
        ControlViaticosApp.LiquidacionesWS.Liquidar CrearLiquidacion(System.DateTime FeLiquidacion, int CoSolicitud, double SsTotalAsignado, double SsTotalUtilizado, double SsOtrosGastos, ControlViaticosApp.LiquidacionesWS.Item[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidaciones/ListarLiquidaciones", ReplyAction="http://tempuri.org/ILiquidaciones/ListarLiquidacionesResponse")]
        System.Collections.Generic.List<ControlViaticosApp.LiquidacionesWS.Liquidar> ListarLiquidaciones();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILiquidacionesChannel : ControlViaticosApp.LiquidacionesWS.ILiquidaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LiquidacionesClient : System.ServiceModel.ClientBase<ControlViaticosApp.LiquidacionesWS.ILiquidaciones>, ControlViaticosApp.LiquidacionesWS.ILiquidaciones {
        
        public LiquidacionesClient() {
        }
        
        public LiquidacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LiquidacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiquidacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiquidacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ControlViaticosApp.LiquidacionesWS.Liquidar ObtenerLiquidacion(int CoLiquidacion) {
            return base.Channel.ObtenerLiquidacion(CoLiquidacion);
        }
        
        public ControlViaticosApp.LiquidacionesWS.Liquidar ModificarLiquidacion(int CoLiquidacion, System.DateTime FeLiquidacion, int CoSolicitud, double SsTotalAsignado, double SsTotalUtilizado, double SsOtrosGastos) {
            return base.Channel.ModificarLiquidacion(CoLiquidacion, FeLiquidacion, CoSolicitud, SsTotalAsignado, SsTotalUtilizado, SsOtrosGastos);
        }
        
        public void EliminarLiquidacion(int CoLiquidacion) {
            base.Channel.EliminarLiquidacion(CoLiquidacion);
        }
        
        public ControlViaticosApp.LiquidacionesWS.Liquidar CrearLiquidacion(System.DateTime FeLiquidacion, int CoSolicitud, double SsTotalAsignado, double SsTotalUtilizado, double SsOtrosGastos, ControlViaticosApp.LiquidacionesWS.Item[] items) {
            return base.Channel.CrearLiquidacion(FeLiquidacion, CoSolicitud, SsTotalAsignado, SsTotalUtilizado, SsOtrosGastos, items);
        }

        public System.Collections.Generic.List<ControlViaticosApp.LiquidacionesWS.Liquidar> ListarLiquidaciones()
        {
            return base.Channel.ListarLiquidaciones();
        }
    }
}
