//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarifarioServiceTest.TarifariosServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tarifario", Namespace="http://schemas.datacontract.org/2004/07/TarifarioServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Tarifario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Co_EmpActualizaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Co_TarifaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Co_TipoViaticoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TarifarioServiceTest.TarifariosServices.Ubigeo Co_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Ss_CostoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Co_EmpActualiza {
            get {
                return this.Co_EmpActualizaField;
            }
            set {
                if ((this.Co_EmpActualizaField.Equals(value) != true)) {
                    this.Co_EmpActualizaField = value;
                    this.RaisePropertyChanged("Co_EmpActualiza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Co_Tarifa {
            get {
                return this.Co_TarifaField;
            }
            set {
                if ((this.Co_TarifaField.Equals(value) != true)) {
                    this.Co_TarifaField = value;
                    this.RaisePropertyChanged("Co_Tarifa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Co_TipoViatico {
            get {
                return this.Co_TipoViaticoField;
            }
            set {
                if ((this.Co_TipoViaticoField.Equals(value) != true)) {
                    this.Co_TipoViaticoField = value;
                    this.RaisePropertyChanged("Co_TipoViatico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TarifarioServiceTest.TarifariosServices.Ubigeo Co_Ubigeo {
            get {
                return this.Co_UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.Co_UbigeoField, value) != true)) {
                    this.Co_UbigeoField = value;
                    this.RaisePropertyChanged("Co_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Ss_Costo {
            get {
                return this.Ss_CostoField;
            }
            set {
                if ((this.Ss_CostoField.Equals(value) != true)) {
                    this.Ss_CostoField = value;
                    this.RaisePropertyChanged("Ss_Costo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ubigeo", Namespace="http://schemas.datacontract.org/2004/07/TarifarioServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Ubigeo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Co_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string No_DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Co_Ubigeo {
            get {
                return this.Co_UbigeoField;
            }
            set {
                if ((this.Co_UbigeoField.Equals(value) != true)) {
                    this.Co_UbigeoField = value;
                    this.RaisePropertyChanged("Co_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No_Descripcion {
            get {
                return this.No_DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.No_DescripcionField, value) != true)) {
                    this.No_DescripcionField = value;
                    this.RaisePropertyChanged("No_Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TarifariosServices.ITarifarios")]
    public interface ITarifarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarifarios/listarTarifarios", ReplyAction="http://tempuri.org/ITarifarios/listarTarifariosResponse")]
        TarifarioServiceTest.TarifariosServices.Tarifario[] listarTarifarios();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITarifariosChannel : TarifarioServiceTest.TarifariosServices.ITarifarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TarifariosClient : System.ServiceModel.ClientBase<TarifarioServiceTest.TarifariosServices.ITarifarios>, TarifarioServiceTest.TarifariosServices.ITarifarios {
        
        public TarifariosClient() {
        }
        
        public TarifariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TarifariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TarifariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TarifariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TarifarioServiceTest.TarifariosServices.Tarifario[] listarTarifarios() {
            return base.Channel.listarTarifarios();
        }
    }
}
